# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('password1', models.TextField()),
                ('password2', models.TextField()),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.datetime(2016, 12, 22, 16, 38, 0, 343306, tzinfo=utc))),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 16, 38, 0, 342572, tzinfo=utc)),
        ),
    ]
