# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_auto_20161222_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempuserprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='tempuserprofile',
            name='key_expires',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 16, 45, 23, 809835, tzinfo=utc)),
        ),
    ]
