# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20161222_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='tempuserprofile',
            name='key_expires',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
