# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20161123_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
